### ISSUE TITLE
A JNI ERROR HAS OCCURRED 

### ISSUE THREAD

**Issue by maomc** [sulab999/AppMessenger#2]
![image](https://user-images.githubusercontent.com/20065601/172780897-5bf52500-2003-47e2-819d-d6827eb4be14.png)

**Comment by shengchenyang** [comment]
> ![image](https://user-images.githubusercontent.com/20065601/172780897-5bf52500-2003-47e2-819d-d6827eb4be14.png)

我遇到同样的问题，不知道你解决了没？

**Comment by Xiao-Chen-Whoami** [comment]
这个一看就是java版本的问题啊，4.4.1之后 他换成java11编译了 你要是java8 就下以前的版本就行了

**Comment by shengchenyang** [comment]
> 这个一看就是java版本的问题啊，4.4.1之后 他换成java11编译了 你要是java8 就下以前的版本就行了

嗯嗯，已经清楚了，感谢解答。
