### ISSUE TITLE
java.lang.IllegalArgumentException: Extensions must be non-null and not empty

### ISSUE THREAD

**Issue by hpp0hpp** [sulab999/AppMessenger#4]
浏览文件就报错
![image](https://user-images.githubusercontent.com/54829297/201104618-269a1cfa-478c-4b78-adae-10f2890efffc.png)

**Comment by sulab999** [comment]
暂时只支持直接拖进APP

**Comment by hpp0hpp** [comment]
> 暂时只支持直接拖进APP

拖不进去
