### ISSUE TITLE
移动apk文件到其他目录提示文件正在使用

### ISSUE THREAD

**Issue by MrSean666** [sulab999/AppMessenger#6]
拖入apk之后剪切移动apk文件到其他目录去会提示文件正在使用,请优化
![image](https://user-images.githubusercontent.com/65343978/201439793-ad3d977c-4ab3-421a-b30d-5f993499ea5f.png)

**Comment by sulab999** [comment]
正在优化中

**Comment by sulab999** [comment]
已解决
